In [1]:
# importing necessary libraries
import cv2 
import numpy as np

Part 1(equation 3)

In [2]:
# used leaf85 as mentioned in question(produced using kmap)(used the code provided in lecture)
im = cv2.imread('leaf85.png')  # reading the image
orginal_shape=im.shape  # store the shape of original image

In [3]:
u_color,cnts=np.unique(im.reshape(-1, orginal_shape[2]), axis=0,return_counts=True)  # finding all the distinct colours and the counts of them

In [4]:
# function to find the distance between two colour
def dis(c1, c2):
  d= (c1[0]-c2[0])**2 + (c1[1]-c2[1])**2 + (c1[2]-c2[2])**2
  return d

In [5]:
freq=cnts/np.sum(cnts)  # normalising the frequencies as mentioned in equation
saliency=[]  # creaating list that will store the final saliency values
for dis_clr in u_color:  # for each distinct colour
  d=[]
  for v in u_color:  # finding the distance between that colour and all other colour and storing it as array
    d.append(dis(v,dis_clr))
  d=np.array(d)
  saliency.append(np.sum(d*freq))    ## equation 3

print(saliency)


[57696.523616666665, 54568.722083333334, 55612.09763333334, 55784.78140000001, 47460.28521666667, 57608.29580000001, 56698.49999999999, 57891.33511666666, 59439.84270000001, 60604.429800000005, 52325.772816666664, 59703.4472, 60739.55913333335, 50258.785749999995, 60233.30755000001, 60118.84226666667, 71975.92603333332, 53511.203916666665, 54954.77353333334, 65575.70353333333, 54453.43175000001, 69214.37939999999, 71337.53435, 50532.76725, 66266.63101666667, 70076.56948333333, 68536.16901666667, 69277.57173333333, 48119.77485, 68586.39026666667, 71250.77436666665, 67593.81506666666, 65849.62741666666, 71736.42804999999, 48719.04543333333, 50407.22696666667, 70565.40901666666, 67437.46746666667, 49533.7526, 49028.13256666667, 46724.557, 63388.86196666667, 51638.190316666674, 48637.034250000004, 71619.63854999999, 48082.12663333333, 56747.47105000001, 49679.068100000004, 68058.1331, 53163.51818333333, 51818.36294999999, 52143.48455000001, 56280.06923333334, 59385.88345, 68099.34400000001

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in ubyte_scalars
  


In [6]:
# the saliency values got are not in range of 0-255, bringing it to the required range
saliency=np.array(saliency)
ma=max(saliency)
mi=min(saliency)
saliency = 255*(saliency-mi)/(ma-mi)
print(saliency.shape)

(85,)


In [7]:
# Now creating an image, with the saliency value for the given RGB value
new_shape=im.reshape(-1, orginal_shape[2])

sal= np.zeros_like(new_shape)
sal=np.sum(sal,axis=1)  # summing it for axis 1, so that [0,0,0] becomes 0 only. leaving image with single channel

for i in range(len(saliency)):  # for every saliency value, go through every pixel and check the colour value, store the saliency value for it in new sal
  [c1, c2 ,c3]=u_color[i]
  s=saliency[i]
  for j in range(len(sal)):
    [p1,p2,p3]=new_shape[j]
    if(c1==p1 and c2==p2 and c3==p3):  # check if the colour of pixel matches
      sal[j]=s

In [8]:
final_sal=sal.reshape(orginal_shape[0],orginal_shape[1])  # making to the required original image size

In [9]:
cv2.imwrite('output1Q1.png',final_sal) # saving the image as required

True

Part 2(equation 5)

In [ ]:
# unzip the given zip, make few changes to get the seg_tree from the BigTree.jpg

In [10]:
!unzip pegbis.zip

Archive:  pegbis.zip
   creating: pegbis/
   creating: pegbis/.git/
   creating: pegbis/.git/branches/
   creating: pegbis/.git/hooks/
  inflating: pegbis/.git/hooks/update.sample  
  inflating: pegbis/.git/hooks/pre-commit.sample  
  inflating: pegbis/.git/hooks/applypatch-msg.sample  
  inflating: pegbis/.git/hooks/pre-rebase.sample  
  inflating: pegbis/.git/hooks/pre-merge-commit.sample  
  inflating: pegbis/.git/hooks/pre-applypatch.sample  
  inflating: pegbis/.git/hooks/pre-push.sample  
  inflating: pegbis/.git/hooks/prepare-commit-msg.sample  
  inflating: pegbis/.git/hooks/pre-receive.sample  
  inflating: pegbis/.git/hooks/commit-msg.sample  
  inflating: pegbis/.git/hooks/post-update.sample  
  inflating: pegbis/.git/hooks/fsmonitor-watchman.sample  
   creating: pegbis/.git/info/
  inflating: pegbis/.git/info/exclude  
  inflating: pegbis/.git/description  
   creating: pegbis/.git/refs/
   creating: pegbis/.git/refs/heads/
  inflating: pegbis/.git/refs/heads/master  
   c

In [11]:
# change path to image in file main.py at line 102
# make changes to save the segmented image
# cv2.imwrite('seg_tree.png',segmented_image)
# run the code

In [12]:
!python3 pegbis/main.py

Loading is done.
processing...
Height:  482
Width:   1024
Execution time: 0 minute(s) and 43 seconds
<Figure size 640x480 with 2 Axes>
[[[  9   9   9]
  [  9   9   9]
  [  9   9   9]
  ...
  [213 213 213]
  [213 213 213]
  [213 213 213]]

 [[  9   9   9]
  [  9   9   9]
  [  9   9   9]
  ...
  [213 213 213]
  [213 213 213]
  [213 213 213]]

 [[  9   9   9]
  [  9   9   9]
  [  9   9   9]
  ...
  [213 213 213]
  [213 213 213]
  [213 213 213]]

 ...

 [[188 188 188]
  [188 188 188]
  [188 188 188]
  ...
  [188 188 188]
  [188 188 188]
  [188 188 188]]

 [[188 188 188]
  [188 188 188]
  [188 188 188]
  ...
  [188 188 188]
  [188 188 188]
  [188 188 188]]

 [[188 188 188]
  [188 188 188]
  [188 188 188]
  ...
  [188 188 188]
  [188 188 188]
  [188 188 188]]]


In [13]:
im = cv2.imread('BigTree.jpg')
im_seg= cv2.imread('seg_tree.png')
orginal_shape=im.shape
r_color,cnts=np.unique(im_seg.reshape(-1, orginal_shape[2]), axis=0,return_counts=True)

In [14]:
print(r_color.shape)

# need to store regions with all there colours and frequency
REGIONS=[]
for i in range(len(r_color)):
  REGIONS.append([])

# print(orginal_shape[0],orginal_shape[1], im[orginal_shape[0]-1][orginal_shape[1]-1])

for i in range(orginal_shape[0]):
  for j in range(orginal_shape[1]):
    # for every pixel, check the colour with region colour, and store position for that region
    [c1, c2 ,c3]=im_seg[i][j]
    for r in range(len(r_color)):
      [p1, p2 ,p3] = r_color[r]
      if(c1==p1 and c2==p2 and c3==p3):
        REGIONS[r].append(im[i][j])  # storing the colour for that region
        break

# store frequency of colours of each region,and also store each colour
RFREQ=[]
RDCLR=[]
for r in range(len(r_color)):
  te=np.array(REGIONS[r])
  r_c,cs=np.unique(te, axis=0,return_counts=True)
  cs=cs/np.sum(cs)
  RFREQ.append(cs)
  RDCLR.append(r_c)


(63, 3)


In [15]:
# distance between two colour(very slow, later did not used it)
def dis(c1, c2):
  d= (c1[0]-c2[0])**2 + (c1[1]-c2[1])**2 + (c1[2]-c2[2])**2
  return d


# function to find distance between two regions(equation 6)
def dis_region(r1,r2):
  s=[]
  for i in range(len(RDCLR[r1])):
    d=  RFREQ[r1][i] * RFREQ[r2] * np.sum((RDCLR[r1][i]-RDCLR[r2])**2,axis=1)
    s.append(np.sum(d))
  s=np.array(s)
  return(np.sum(s))
  # s=0
  # for i in range(len(RDCLR[r1])):
  #   for j in range(len(RDCLR[r2])):
  #     s+= RFREQ[r1][i] * RFREQ[r2][j] * dis(RDCLR[r1][i],RDCLR[r2][j])
  # return s

# finding the frequency/normalising the counts of the regions(as stated in paper)
freq=cnts/np.sum(cnts)

saliency_r=[]  # this will store the final saliency values for each region
for i in range(len(r_color)):
  d=[]
  for j in range(len(r_color)):
    if(i!=j):
      c=dis_region(i,j)  # calling the function to get the distance between the regions as stated in equation 6
      d.append(c*freq[j])  ## EQUATION 5
  d=np.array(d)
  saliency_r.append(np.sum(d))
    
saliency_r=np.array(saliency_r)
print(saliency_r)

[318.68145559 313.13035205 160.47468609 320.18150589 318.66282819
 318.23347505 311.50405966 318.43931437 317.87922073 312.94116452
 312.07236269 315.50300125 314.30954288 312.25203216 310.03889212
 309.70483489 315.14731171 292.47550734 316.95636284 319.16872438
 311.58024023 309.93985655 313.28888552 314.39542115 312.53479207
 309.90826039 311.3821845  313.21360904 313.482307   316.30500708
 317.03923818 311.89248499 319.17820323 317.13235309 315.43752399
 315.40611793 292.37472227 318.08638179 310.83072694 312.57607155
 317.12663159 316.85238809 315.33119518 310.41894781 316.81538758
 306.54283399 317.8358726  251.32595522 318.31681634 295.32872974
 230.84694512 305.62441549 315.2479048  309.2072475  271.02616895
 315.86172444 317.59198621 315.81850601 312.8579082  301.69013768
 315.53454393 312.79285024 322.07667069]


In [16]:
# again bringing the values of saliency in the range 0-255
ma=max(saliency_r)
mi=min(saliency_r)
saliency_r = 255*(saliency_r-mi)/(ma-mi)

new_shape=im_seg.reshape(-1, orginal_shape[2])

sal= np.zeros_like(new_shape)
sal=np.sum(sal,axis=1)
# repeating the steps as in part 1
for i in range(len(saliency_r)):
  [c1, c2 ,c3]=r_color[i]
  s=saliency_r[i]
  for j in range(len(sal)):
    [p1,p2,p3]=new_shape[j]
    if(c1==p1 and c2==p2 and c3==p3):
      sal[j]=s

final_sal=sal.reshape(orginal_shape[0],orginal_shape[1])
cv2.imwrite('output2Q1.png',final_sal)  # saving the final saliency as image

True